// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnG4AMJeHzsGIJRjo09Vx9XaGXWNWCg48',
    appId: '1:227258159442:android:5c60724fe6af92d5fc6a8b',
    messagingSenderId: '227258159442',
    projectId: 'skillbridge-9c999',
    storageBucket: 'skillbridge-9c999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlBZ3MRA5V3KyIEHIPSHkE8sRFphEwlFc',
    appId: '1:227258159442:ios:23ef61fdbc8fe9b6fc6a8b',
    messagingSenderId: '227258159442',
    projectId: 'skillbridge-9c999',
    storageBucket: 'skillbridge-9c999.firebasestorage.app',
    iosBundleId: 'com.skillbridge.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlBZ3MRA5V3KyIEHIPSHkE8sRFphEwlFc',
    appId: '1:227258159442:ios:23ef61fdbc8fe9b6fc6a8b',
    messagingSenderId: '227258159442',
    projectId: 'skillbridge-9c999',
    storageBucket: 'skillbridge-9c999.firebasestorage.app',
    iosBundleId: 'com.skillbridge.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg0qpIPaCYkzswieE6RUgIRy2QynC6K_s',
    appId: '1:227258159442:web:8ed47f36556637cdfc6a8b',
    messagingSenderId: '227258159442',
    projectId: 'skillbridge-9c999',
    authDomain: 'skillbridge-9c999.firebaseapp.com',
    storageBucket: 'skillbridge-9c999.firebasestorage.app',
  );

}