class AppSkills {
  static const List<String> all = [
    // 💻 Web Development
    "React Frontend",
    "Angular Frontend",
    "Vue.js Frontend",
    "Next.js Development",
    "HTML & CSS",
    "Tailwind CSS",
    "Node.js Backend",
    "Laravel Backend",
    "Django Backend",
    "REST API Design",
    "GraphQL",
    "TypeScript",

    // 📱 Mobile Development
    "Flutter Development",
    "React Native",
    "iOS (Swift)",
    "Android (Kotlin)",
    "Firebase Integration",

    // ⛓️ Blockchain & Web3
    "Solidity Smart Contracts",
    "Ethereum Development",
    "Foundry Framework",
    "Hardhat Framework",
    "Web3.js / Ethers.js",
    "NFT Development",
    "DeFi Protocols",
    "IPFS & Decentralized Storage",

    // 📊 Data & Analytics
    "Python for Data Science",
    "Pandas & NumPy",
    "SQL & Database Design",
    "Power BI Dashboards",
    "Tableau Visualization",
    "Excel Financial Modeling",
    "Google Sheets Automation",
    "Machine Learning (Scikit-learn)",
    "Deep Learning (TensorFlow)",
    "Data Cleaning & EDA",

    // ☁️ Cloud & DevOps
    "AWS Cloud Services",
    "Google Cloud Platform",
    "Docker & Containerization",
    "CI/CD Pipelines",
    "Linux & Bash Scripting",
    "Nginx & Server Config",

    // 🎨 Design
    "Figma UI Design",
    "Figma Prototyping",
    "UX Research",
    "Design Systems",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Motion Design (After Effects)",
    "Video Editing (Premiere Pro)",
    "3D Modeling (Blender)",

    // 📈 Business & Finance
    "Financial Analysis",
    "Business Valuation",
    "Investment Research",
    "Accounting Basics",
    "Startup Pitching",
    "Product Management",
    "Agile & Scrum",

    // 🗣️ Languages
    "Arabic Language",
    "English Language",
    "French Language",
    "Spanish Language",
    "German Language",
    "Italian Language",
    "Chinese (Mandarin)",
    "Japanese Language",

    // 🎯 Other
    "Public Speaking",
    "Technical Writing",
    "SEO & Content Strategy",
    "Digital Marketing",
    "Cybersecurity Basics",
    "Penetration Testing",
    "Game Development (Unity)",
  ];

  // Group skills by category for the picker UI
  static const Map<String, List<String>> byCategory = {
    "Web Development": [
      "React Frontend",
      "Angular Frontend",
      "Vue.js Frontend",
      "Next.js Development",
      "HTML & CSS",
      "Tailwind CSS",
      "Node.js Backend",
      "Laravel Backend",
      "Django Backend",
      "REST API Design",
      "GraphQL",
      "TypeScript",
    ],
    "Mobile Development": [
      "Flutter Development",
      "React Native",
      "iOS (Swift)",
      "Android (Kotlin)",
      "Firebase Integration",
    ],
    "Blockchain & Web3": [
      "Solidity Smart Contracts",
      "Ethereum Development",
      "Foundry Framework",
      "Hardhat Framework",
      "Web3.js / Ethers.js",
      "NFT Development",
      "DeFi Protocols",
      "IPFS & Decentralized Storage",
    ],
    "Data & Analytics": [
      "Python for Data Science",
      "Pandas & NumPy",
      "SQL & Database Design",
      "Power BI Dashboards",
      "Tableau Visualization",
      "Excel Financial Modeling",
      "Google Sheets Automation",
      "Machine Learning (Scikit-learn)",
      "Deep Learning (TensorFlow)",
      "Data Cleaning & EDA",
    ],
    "Cloud & DevOps": [
      "AWS Cloud Services",
      "Google Cloud Platform",
      "Docker & Containerization",
      "CI/CD Pipelines",
      "Linux & Bash Scripting",
      "Nginx & Server Config",
    ],
    "Design": [
      "Figma UI Design",
      "Figma Prototyping",
      "UX Research",
      "Design Systems",
      "Adobe Illustrator",
      "Adobe Photoshop",
      "Motion Design (After Effects)",
      "Video Editing (Premiere Pro)",
      "3D Modeling (Blender)",
    ],
    "Business & Finance": [
      "Financial Analysis",
      "Business Valuation",
      "Investment Research",
      "Accounting Basics",
      "Startup Pitching",
      "Product Management",
      "Agile & Scrum",
    ],
    "Languages": [
      "Arabic Language",
      "English Language",
      "French Language",
      "Spanish Language",
      "German Language",
      "Italian Language",
      "Chinese (Mandarin)",
      "Japanese Language",
    ],
    "Other": [
      "Public Speaking",
      "Technical Writing",
      "SEO & Content Strategy",
      "Digital Marketing",
      "Cybersecurity Basics",
      "Penetration Testing",
      "Game Development (Unity)",
    ],
  };
}
